---
title: "Quartile Survival"
author: "Dave Hein"
date: "3/20/2020"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(car)
library(lattice)
library(formattable)

set.seed(123)

#reading in data
colonchemo <- read.delim2("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/Github Repository/SEER-Survival-Rates-Over-Time/colonchemo.txt")

panchemo <- read.delim2("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/Github Repository/SEER-Survival-Rates-Over-Time/lungchemo.txt")

lungchemo <- read.delim2("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/Github Repository/SEER-Survival-Rates-Over-Time/panchemo.txt")

```


## Helpful Functions
```{r}
##Function to plot w/bootstrapped SE
plotbootse <- function(fit,samp_distn,meds,lim) {
#New plot with bootstrapped SE
      
      #Getting estimated Co-efficeints
      mat <- cbind(coef(fit))
      
      #making table of mx+b
      lines <- c((mat[1]),(mat[5]))
      lines <- rbind(lines,c((mat[1]+mat[2]),(mat[5]+mat[6])))
      lines <- rbind(lines,c((mat[1]+mat[3]),(mat[5]+mat[7])))
      lines <- rbind(lines,c((mat[1]+mat[4]),(mat[5]+mat[8])))
      row.names(lines) <- c("quartile1","quartile2","quartile3","quartile4")
      lines <-  as.data.frame(lines)
      names(lines)[1] <- "yIntercept"
      names(lines)[2] <- "mSlope"
      
      #Boot data
      bootci <- samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)
      bootci
      #Entering boot data into 
      lines$lowery <- 0
      lines$lowerm <- 0
      lines$uppery <- 0
      lines$upperm <- 0
      
      #q1 y lower & upper
      lines[1,3] <- (lines[1,1] - bootci[1,1])
      lines[1,5] <- (lines[1,1] + bootci[1,1])
      
      #q2 y lower & upper
      lines[2,3] <- (lines[2,1] - (bootci[1,1] + bootci[1,2]))
      lines[2,5] <- (lines[2,1] + (bootci[1,1] + bootci[1,2]))
      
      #q3 y lower & upper
      lines[3,3] <- (lines[3,1] - (bootci[1,1] + bootci[1,3]))
      lines[3,5] <- (lines[3,1] + (bootci[1,1] + bootci[1,3]))
      
      #q4 y lower & upper
      lines[4,3] <- (lines[4,1] - (bootci[1,1] + bootci[1,4]))
      lines[4,5] <- (lines[4,1] + (bootci[1,1] + bootci[1,4]))
      
      #q1 m lower & upper
      lines[1,4] <- (lines[1,2] - bootci[1,5])
      lines[1,6] <- (lines[1,2] + bootci[1,5])
     
      #q2 m lower & upper
      lines[2,4] <- (lines[2,2] - (bootci[1,5] + bootci[1,6]))
      lines[2,6] <- (lines[2,2] + (bootci[1,5] + bootci[1,6]))
      
      #q3 m lower & upper
      lines[3,4] <- (lines[3,2] - (bootci[1,5] + bootci[1,7]))
      lines[3,6] <- (lines[3,2] + (bootci[1,5] + bootci[1,7]))
       
      #q4 m lower & upper
      lines[4,4] <- (lines[4,2] - (bootci[1,5] + bootci[1,8]))
      lines[4,6] <- (lines[4,2] + (bootci[1,5] + bootci[1,8]))
     
    
      ggplot() +  geom_point(data=meds, aes(x=Year.of.diagnosis,y=meds,group=quartile,color=quartile),size=1.2) + geom_smooth(data =    meds,aes(x=Year.of.diagnosis,y=meds,group=quartile,color=quartile),method="lm",se = FALSE)  + labs(x="Year of Diagnosis",y="Median Overall Survival (Months)",color="Quartile") +
        theme_test() +
        theme(axis.text.x=element_text(size=rel(1.5)),axis.text.y=element_text(size=rel(1.5)) )+
      
        #q4 min & max
        geom_abline(data = lines, aes(slope=lines[4,4],intercept= (lines[4,3]-lines[4,4]*1990)), linetype="dashed",color = 404040) +
        geom_abline(data = lines, aes(slope=lines[4,6],intercept= (lines[4,5]-lines[4,6]*1990)), linetype="dashed",color = 404040) +
    
        #q3
        geom_abline(data = lines, aes(slope=lines[3,4],intercept= (lines[3,3]-lines[3,4]*1990)), linetype="dashed",color = 404040) +
        geom_abline(data = lines, aes(slope=lines[3,6],intercept= (lines[3,5]-lines[3,6]*1990)), linetype="dashed",color = 404040) +
      
        #q2
        geom_abline(data = lines, aes(slope=lines[2,4],intercept= (lines[2,3]-lines[2,4]*1990)), linetype="dashed",color = 404040) +
        geom_abline(data = lines, aes(slope=lines[2,6],intercept= (lines[2,5]-lines[2,6]*1990)), linetype="dashed",color = 404040) +
      
        #q1
        geom_abline(data = lines, aes(slope=lines[1,4],intercept= (lines[1,3]-lines[1,4]*1990)), linetype="dashed",color = 404040) +
        geom_abline(data = lines, aes(slope=lines[1,6],intercept= (lines[1,5]-lines[1,6]*1990)), linetype="dashed",color = 404040) +
        
        #WILL NEED TO CHANGE THIS FOR EACH GRAPH
        geom_rect(data = lines, xmin=1980,ymin=0,xmax=1989.8,ymax=200,color="white",fill="white")+
        geom_rect(data = lines, xmin=lim,ymin=0,xmax=2020,ymax=200,color="white",fill="white")
      
}


#Function to convert SEER age category to a numeric value
agenumeric <- function(ntils) {
ntils <- ntils %>% mutate(Age.recode.with..1.year.olds=str_remove_all(Age.recode.with..1.year.olds,regex(" years")))%>% mutate(Age.recode.with..1.year.olds,lowerage=substr(Age.recode.with..1.year.olds,start=1,stop=2))%>%
mutate(Age.recode.with..1.year.olds,upperage=substr(Age.recode.with..1.year.olds,start=4,stop=5))%>%
mutate(lowerage,lowerage=as.numeric(lowerage))%>%mutate(upperage,upperage=as.numeric(upperage))%>%
mutate(lowerage,age= ifelse( (lowerage==85 | lowerage==0) ,85,(lowerage+upperage)/2))
}
```



# Colorectal
#### Colon cancer Patients who received chemotherapy 
```{r}  
# Median survival by quartile of people who got chemo 
#making percentiles
ntilscolochemo <- colonchemo%>% filter(Year.of.diagnosis < 2011 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
mutate(Survival.months, quartile = ntile(Survival.months,4))

#finding median of each percentile
medscolochemo <- ntilscolochemo  %>% dplyr::group_by(Year.of.diagnosis,quartile) %>% dplyr::summarize(meds = median(Survival.months))

#overall median survival
overallcolochemo <- colonchemo %>% filter(Year.of.diagnosis < 2010 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
summarize(meds = median(Survival.months))
    
#Ploting change in median surv over time
ggplot() + geom_line(data=medscolochemo, aes(x=Year.of.diagnosis,y=meds,group=quartile,color=quartile),size=1.2) + labs(x="Year of Diagnosis",y="Median Overall Survival (Months)",color="Quartile") 
   #geom_line(data=overallcolochemo,aes(x=Year.of.diagnosis,y=meds),color="#249c62",size=1.2)
  
#GLM
colochemoyearadjust <- medscolochemo 
colochemoyearadjust$year <- colochemoyearadjust$Year.of.diagnosis - 1990
colochemoyearadjust$quartile <- factor(colochemoyearadjust$quartile)
   
fitcolochemo <- lm(meds ~ quartile + year + quartile:year,colochemoyearadjust)
summary(fitcolochemo)
   
#test normally distributed residuals
hist(residuals(fitcolochemo),breaks=20)
    
#test for homoskedasticity
xyplot(resid(fitcolochemo) ~ fitted(fitcolochemo) | colochemoyearadjust$quartile,
          xlab = "Fitted Values",
          ylab = "Residuals",
          main = "Residual Diagnostic Plot",
          panel = function(x,y,...)
          {
            panel.grid(h= -1, v= -1)
            panel.abline(h=0)
            panel.xyplot(x,y,...)
          }
          )
   
#Bootsrapped SE
samp_distn<-replicate(5000,{
      boot_dat <- colochemoyearadjust[sample(nrow(colochemoyearadjust),replace=TRUE),]
      fitcc<- lm(meds ~ quartile + year + quartile:year,data=boot_dat)
      coef(fitcc)
      })
   
samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)

#95% CI 
samp_distn%>%t%>%as.data.frame%>%gather%>%group_by(key)%>%
    summarize(lower=quantile(value,.025), upper=quantile(value,.975))
   
#Plot with bootstrapped SE
plotbootse(fitcolochemo,samp_distn,medscolochemo,2010.1)
  

```



# Pancreas
#### Pan Patients who received chemotherapy
```{r}

# Median surrvival by quartile of people who got chemo 
#making percentiles
ntilspanchemo <- panchemo%>% filter(Year.of.diagnosis < 2013 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
mutate(Survival.months, quartile = ntile(Survival.months,4))

#finding median of each percentile
medspanchemo <- ntilspanchemo  %>% group_by(Year.of.diagnosis,quartile) %>% summarize(meds = median(Survival.months))

#overall median survival
overallpanchemo <- panchemo %>% filter(Year.of.diagnosis < 2011 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
summarize(meds = median(Survival.months))

#Ploting change in median surv over time
ggplot() + geom_line(data=medspanchemo, aes(x=Year.of.diagnosis,y=meds,group=quartile,color=quartile),size=1.2) + labs(x="Year of Diagnosis",y="Median Overall Survival (Months)",color="Quartile") 
   
#GLM
panchemoyearadjust <- medspanchemo
panchemoyearadjust$year <- panchemoyearadjust$Year.of.diagnosis - 1990
panchemoyearadjust$quartile <- factor(panchemoyearadjust$quartile)
    
fitpanchemo <- lm(meds ~ quartile + year + quartile:year,panchemoyearadjust)
summary(fitpanchemo)
   
#test normally distributed residuals
hist(residuals(fitpanchemo),breaks=20)
    
#test for homoskedasticity
xyplot(resid(fitpanchemo) ~ fitted(fitpanchemo) | panchemoyearadjust$quartile,
          xlab = "Fitted Values",
          ylab = "Residuals",
          main = "Residual Diagnostic Plot",
          panel = function(x,y,...)
          {
            panel.grid(h= -1, v= -1)
            panel.abline(h=0)
            panel.xyplot(x,y,...)
          }
          )
   
#Bootsrapped SE
samp_distn<-replicate(5000,{
  boot_dat <- panchemoyearadjust[sample(nrow(panchemoyearadjust),replace=TRUE),]
  fitc<- lm(meds ~ quartile + year + quartile:year,data=boot_dat)
  coef(fitc)
  })
   
samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)

#95% CI 
samp_distn%>%t%>%as.data.frame%>%gather%>%group_by(key)%>%
    summarize(lower=quantile(value,.025), upper=quantile(value,.975))

#New plot with bootstrapped SE
plotbootse(fitpanchemo,samp_distn,medspanchemo,2012.1)  
   
```



# Lung
#### Lung Patients who received chemotherapy
```{r}
# Median surrvival by quartile of people who got chemo 
#making percentiles
ntilslungchemo <- lungchemo%>% filter(Year.of.diagnosis < 2012 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
mutate(Survival.months, quartile = ntile(Survival.months,4))

#finding median of each percentile
medslungchemo <- ntilslungchemo  %>% group_by(Year.of.diagnosis,quartile) %>% summarize(meds = median(Survival.months))

#overall median survival
overalllungchemo <- lungchemo %>% filter(Year.of.diagnosis < 2011 & Year.of.diagnosis>1989) %>% group_by(Year.of.diagnosis) %>% 
summarize(meds = median(Survival.months))

#Ploting change in median surv over time
ggplot() + geom_line(data=medslungchemo, aes(x=Year.of.diagnosis,y=meds,group=quartile,color=quartile),size=1.2) + labs(x="Year of Diagnosis",y="Median Overall Survival (Months)",color="Quartile")
    #+geom_line(data=overalllungchemo,aes(x=Year.of.diagnosis,y=meds),color="#249c62",size=1.2)

#GLM
lungchemoyearadjust <- medslungchemo
lungchemoyearadjust$year <- lungchemoyearadjust$Year.of.diagnosis - 1990
lungchemoyearadjust$quartile <- factor(lungchemoyearadjust$quartile)
   
fitlungchemo <- lm(meds ~ quartile + year + quartile:year,lungchemoyearadjust)
summary(fitlungchemo)
   
#test normally distributed residuals
hist(residuals(fitlungchemo),breaks=20)
    
#test for homoskedasticity
xyplot(resid(fitlungchemo) ~ fitted(fitlungchemo) | lungchemoyearadjust$quartile,
          xlab = "Fitted Values",
          ylab = "Residuals",
          main = "Residual Diagnostic Plot",
          panel = function(x,y,...)
          {
            panel.grid(h= -1, v= -1)
            panel.abline(h=0)
            panel.xyplot(x,y,...)
          }
          )
   
#Bootsrapped SE
samp_distn<-replicate(5000,{
      boot_dat <- lungchemoyearadjust[sample(nrow(lungchemoyearadjust),replace=TRUE),]
      fitc<- lm(meds ~ quartile + year + quartile:year,data=boot_dat)
      coef(fitc)
      })
   
samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)

#95% CI 
samp_distn%>%t%>%as.data.frame%>%gather%>%group_by(key)%>%
  summarize(lower=quantile(value,.025), upper=quantile(value,.975))
      
#New plot with bootstrapped SE
plotbootse(fitlungchemo,samp_distn,medslungchemo,2011.1)
    
```
